name: Semantic PR Validation

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  validate:
    name: Validate PR title
    uses: ItsMestro/devtools/.github/workflows/shared-semantic-pr-validation.yml@21967214a9e03d0d3646e5209bc35a06dd3cf6dc # main
    permissions:
      pull-requests: read
    secrets: inherit
